"""

Django settings for gweb project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load only backend-local .env (gweb/gweb/.env)
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE_PATH = BASE_DIR / '.env'

print(f"[DEBUG] Loading env from: {ENV_FILE_PATH}")
# Load only gweb/gweb/.env
load_dotenv(ENV_FILE_PATH)

# Debug: print database config
print(f"[DEBUG] DATABASE_URL in env: {os.getenv('DATABASE_URL')}")
print(f"[DEBUG] DB_NAME in env: {os.getenv('DB_NAME')}")

SECRET_KEY = os.getenv('SECRET_KEY' , "bGoXs4fFx7P9XwpW30g8Enm-bfEx9-1jly5-hZxnh6vECcbQVUEXYRqP54ptZmALWFg")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable must be set for security!")

SITE_DOMAIN = os.getenv("SITE_DOMAIN", "localhost:3000")
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'
USE_R2_STORAGE = os.getenv('USE_R2_STORAGE', 'false').lower() == 'true'


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


QUIZ_SOURCE_MAX_CHARS = _env_int("QUIZ_SOURCE_MAX_CHARS", 7000)
SUMMARY_SOURCE_MAX_CHARS = _env_int("SUMMARY_SOURCE_MAX_CHARS", 9000)
CHAT_OPENAI_MODEL = os.getenv("CHAT_OPENAI_MODEL", "gpt-4o-mini")
TITLE_OPENAI_MODEL = os.getenv("TITLE_OPENAI_MODEL", "gpt-4o-mini")
QUIZ_OPENAI_MODEL = os.getenv("QUIZ_OPENAI_MODEL", "gpt-4o-mini")
SUMMARY_OPENAI_MODEL = os.getenv("SUMMARY_OPENAI_MODEL", "gpt-4o-mini")
TTS_OPENAI_MODEL = os.getenv("TTS_OPENAI_MODEL", "gpt-4o-mini-tts")
GOOGLE_WEB_CLIENT_ID = os.getenv("GOOGLE_WEB_CLIENT_ID", "")

def _normalize_host(value: str) -> str:
    host = value.strip()
    if not host:
        return ""
    if "://" in host:
        host = host.split("://", 1)[1]
    host = host.split("/", 1)[0]
    host = host.split(":", 1)[0]
    return host.strip()


allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = []
for raw_host in allowed_hosts_env.split(","):
    host = _normalize_host(raw_host)
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Render sets this automatically for the deployed web service.
render_host = _normalize_host(os.getenv("RENDER_EXTERNAL_HOSTNAME", ""))
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

if not DEBUG:
    ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host != "*"]

PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
FRONTEND_CALLBACK_URL = os.getenv('FRONTEND_CALLBACK_URL', 'http://localhost:3000/payment/callback')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'g_auth',
    'chat',
    'files',
    'payments',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]
if USE_R2_STORAGE:
    INSTALLED_APPS.append('storages')

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@glinax.com'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '60/minute',
    },
    #'EXCEPTION_HANDLER': 'gweb.gweb.exception_handlers.custom_exception_handler',
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gweb.urls'

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in debug mode
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://qwikstudi.com",
    "https://www.qwikstudi.com",
    "https://glinax-frontend.onrender.com",
]
# Add from environment variable if provided
env_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
if env_origins:
    for origin in env_origins.split(','):
        origin = origin.strip()
        if origin and origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# For development - allow localhost:8000 (the backend itself)
CORS_ALLOWED_ORIGINS.append("http://localhost:8000")
CORS_ALLOWED_ORIGINS.append("http://127.0.0.1:8000")
from datetime import timedelta

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": True,
        },
        "chat": {
            "handlers": ["console"],
            "level": os.getenv("CHAT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "g_auth": {
            "handlers": ["console"],
            "level": os.getenv("G_AUTH_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "openai": {"level": os.getenv("OPENAI_LOG_LEVEL", "WARNING")},
        "httpx": {"level": os.getenv("HTTPX_LOG_LEVEL", "WARNING")},
        "httpcore": {"level": os.getenv("HTTPCORE_LOG_LEVEL", "WARNING")},
        "urllib3": {"level": os.getenv("URLLIB3_LOG_LEVEL", "WARNING")},
        "boto3": {"level": os.getenv("BOTO3_LOG_LEVEL", "WARNING")},
        "botocore": {"level": os.getenv("BOTOCORE_LOG_LEVEL", "WARNING")},
        "s3transfer": {"level": os.getenv("S3TRANSFER_LOG_LEVEL", "WARNING")},
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_SERIALIZER": "g_auth.serializers.CustomTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "g_auth.serializers.CustomTokenRefreshSerializer",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gweb.wsgi.application'

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'gwebDB'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

if 'DATABASE_URL' in os.environ:
    try:
        database_config = dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
        if database_config:
            DATABASES['default'] = database_config
    except Exception as e:
        print(f"Warning: DATABASE_URL configuration failed: {e}")
        print("Falling back to local database configuration")

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if USE_R2_STORAGE:
    R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
    R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
    R2_BUCKET_NAME = os.getenv('R2_BUCKET_NAME', '')
    R2_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL', '')

    missing_r2 = [
        name for name, value in (
            ('R2_ACCESS_KEY_ID', R2_ACCESS_KEY_ID),
            ('R2_SECRET_ACCESS_KEY', R2_SECRET_ACCESS_KEY),
            ('R2_BUCKET_NAME', R2_BUCKET_NAME),
            ('R2_ENDPOINT_URL', R2_ENDPOINT_URL),
        ) if not value
    ]
    if missing_r2:
        raise RuntimeError(
            f"USE_R2_STORAGE=true but missing required env vars: {', '.join(missing_r2)}"
        )

    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL
    AWS_S3_REGION_NAME = 'auto'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False

    STORAGES = {
        'default': {
            'BACKEND': 'gweb.storage_backends.R2MediaStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
